[package]
name = "rakrs"
version = "0.1.0"
authors = ["Bavfalcon9"]
edition = "2018"

[dependencies]
rand = "0.8.3"
binary_utils = { git = "https://github.com/NetrexMC/BinaryUtil", branch = "v2" }
tokio = { version = "1.10.0", features = ["time", "net", "rt"] }
byteorder = "1.4.3"
